.TH SIMPLE_LCDPP 1 "July 2020" Linux "User Manuals"                                  
.SH NAME                                                                     
simple_lcdpp \- An utility to write text on HD44780 LCD displays.
.SH SYNOPSIS                                                                 
.B  simple_lcdpp [-t text] [-r row] [-i] 
           [-d device] [-a device hex address] [-R row_max] [-c col_max]
           [-h] 
.SH DESCRIPTION                                                              
simple_lcdpp can send text to a specific row of an HD44780 compatible display.  It supports many display simultaneously, setting accordingly address and device special file path.
.SH OPTIONS                                                       
.IP -c\ col_max
Specifies the maximum number of columns available.
.IP -R\ row_max
Specifies the maximum number of rows available.
.IP -t\ text 
Specifies the text string intended to be shown on the display.
.IP -r\ row_number
Specifies the row number ( starting from 1 ) to select the destination of the text string.
.IP -i 
Sends the init sequence to the display. Mandatory the first time, it initializes the device and clearing the present texr string.  
.IP -d\ device                                                                      
Specifies the special file, the display interface on /dev.
.IP -a\ address
Specifies the address on the I2C chain assigned to the display.
.IP -h
A short description of simple_lcdpp command line syntax.
.SH BUGS                                                                     
This program is a beta, please send any bug, with information to reproduce it, to the address specified below.
.SH AUTHOR                                                                   
Gabriele Bonacini <gabriele.bonacini@protonmail.com>